apiVersion: v1
kind: Service
metadata:
        name: {{ .Values.apisix.name }}-service
        labels:
                app: {{ .Values.apisix.name }}
        namespace: {{ .Values.namespace }}
spec:
        type: NodePort
        ports:
                - port: {{ .Values.apisix.port }}
                  name: http
        selector:
                app: {{ .Values.apisix.name }}
