apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
        namespace: {{ .Values.namespace }}
        name: {{ .Values.apisix.name }}-ingress
        {{- with .Values.ingress.annotations }}
        annotations:
                {{- toYaml . | nindent 16 }}
        {{- end }}
spec:
        rules:
                {{- range .Values.ingress.hosts }}
                - host:
                  http:
                          paths:
                                  {{- range .paths }}
                                  - path: {{ .path }}
                                    pathType: {{ .pathType }}
                                  {{- end }}
                {{- end }}
                                    backend:
                                            service:
                                                    name: {{ .Values.apisix.name }}-service
                                                    port:
                                                        number: {{ .Values.apisix.port }}
