apiVersion: v1
kind: Secret
metadata:
        name: {{ .Values.keycloak.name }}-secret
        namespace: {{ .Values.namespace }}
type: Opaque
data:
        username: {{ .Values.secrets.keycloak.username }}
        password: {{ .Values.secrets.keycloak.password }}
        db-username: {{ .Values.secrets.db.username }}
        db-password: {{ .Values.secrets.db.password }}
