apiVersion: v1
kind: ConfigMap
metadata:
        name: {{ .Values.keycloak.name }}-configmap
        labels:
                app: {{.Values.app }}
        namespace: {{ .Values.namespace }}
data:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://{{ .Values.postgres.pod }}.{{ .Values.postgres.name }}-service.{{ .Values.namespace }}.svc.cluster.local/{{ .Values.dbName }}
        KC_HTTP_RELATIVE_PATH: "identity"
        KC_PROXY: edge
        KC_HOSTNAME: 5gmeta-platform.eu
        KC_HOSTNAME_PATH: identity
        KC_FEATURES: declarative-user-profile