apiVersion: v1
kind: Service
metadata:
        name: {{ .Values.keycloak.name }}-service
        labels:
                app: {{ .Values.keycloak.name }}
        namespace: {{ .Values.namespace }}
spec:
        type: NodePort
        ports:
                - port: 8080
        selector:
                app: {{ .Values.keycloak.name }}
