routes:
  -
    uri: /identity/*
    upstream:
        nodes:
                "keycloak-service.akka.svc.cluster.local:8080": 1
        type: roundrobin
    priority: 200
  -
    uri: /license-api/*
    upstream:
        nodes:
                "license-service.akka.svc.cluster.local:5000": 1
        type: roundrobin
    priority: 201
    plugins:
        openid-connect:
          access_token_in_authorization_header: false
          client_id: <apisix client id>
          client_secret: <apisix client secret>
          discovery: >-
                  https://<keycloak endpoint>/realms/<realm>/.well-known/openid-configuration
          introspection_endpoint: >-
                  https://<keycloak endpoint>/realms/<realm>/protocol/openid-connect/token/introspect
          scope: "openid profile"
          bearer_only: false
          realm: 5gmeta
          introspection_endpoint_auth_method: client_secret_post
          redirect_uri: "/license-api/redirect"
        cors:
          allow_origins: "*"
  -
    uri: /cloudinstance-api/*
    upstream:
        nodes:
                "cloudinstance-api.vicomtech.svc.cluster.local:5000": 1
        type: roundrobin
    priority: 201
    plugins:
        openid-connect:
          access_token_in_authorization_header: false
          client_id: <apisix client id>
          client_secret: <apisix client secret>
          discovery: >-
                  https://<keycloak endpoint>/realms/<realm>/.well-known/openid-configuration
          introspection_endpoint: >-
                  https://<keycloak endpoint>/realms/<realm>/protocol/openid-connect/token/introspect
          scope: "openid profile"
          bearer_only: false
          realm: 5gmeta
          introspection_endpoint_auth_method: client_secret_post
          redirect_uri: "/cloudinstance-api/redirect"
        cors:
          allow_origins: "*"
  -
    uri: /dataflow-api/*
    upstream:
        nodes:
                "dataflow-api.links.svc.cluster.local:8080": 1
        type: roundrobin
    priority: 201
    plugins:
        openid-connect:
          access_token_in_authorization_header: false
          client_id: <apisix client id>
          client_secret: <apisix client secret>
          discovery: >-
                  https://<keycloak endpoint>/realms/<realm>/.well-known/openid-configuration
          introspection_endpoint: >-
                  https://<keycloak endpoint>/realms/<realm>/protocol/openid-connect/token/introspect
          scope: "openid profile"
          bearer_only: false
          realm: 5gmeta
          introspection_endpoint_auth_method: client_secret_post
          redirect_uri: "/dataflow-api/redirect"
        cors:
          allow_origins: "*"
  -
    uri: /discovery-api/*
    upstream:
        nodes:
                "discovery-api.vicomtech.svc.cluster.local:8080": 1
        type: roundrobin
    priority: 201
    plugins:
        openid-connect:
          access_token_in_authorization_header: false
          client_id: <apisix client id>
          client_secret: <apisix client secret>
          discovery: >-
                  https://<keycloak endpoint>/realms/<realm>/.well-known/openid-configuration
          introspection_endpoint: >-
                  https://<keycloak endpoint>/realms/<realm>/protocol/openid-connect/token/introspect
          scope: "openid profile"
          bearer_only: false
          realm: 5gmeta
          introspection_endpoint_auth_method: client_secret_post
          redirect_uri: "/discovery-api/redirect"
        cors:
          allow_origins: "*"
  -
    uri: /dashboard/*
    upstream:
        nodes:
                "dashboard-service.akka.svc.cluster.local:80": 1
        type: roundrobin
    priority: 201
    plugins:
        openid-connect:
          access_token_in_authorization_header: false
          client_id: <apisix client id>
          client_secret: <apisix client secret>
          discovery: >-
                  https://<keycloak endpoint>/realms/<realm>/.well-known/openid-configuration
          introspection_endpoint: >-
                  https://<keycloak endpoint>/realms/<realm>/protocol/openid-connect/token/introspect
          scope: "openid profile"
          bearer_only: false
          realm: 5gmeta
          introspection_endpoint_auth_method: client_secret_post
          redirect_uri: "/dashboard/redirect"
        cors:
          allow_origins: "*"
#END
